fix compilation error when ERROR_PRINT is enabled
Fix defect introduced in 019b6853237f2ddaf830846a0eb39c0d919504e5 when
the print macro lost the driver pointer it was referencing

Signed-off-by: Cristian Stoica <cristian.stoica@freescale.com>
Change-Id: Ic487ef0dbf23653223515e9f6969ecf9d434593a
Reviewed-on: http://git.am.freescale.net:8181/37404